### ISSUE TITLE
Stacker uses the base angle when stacking relative to "prop"

### ISSUE THREAD

**Issue by dvdvideo1234** [Mista-Tea/improved-stacker#16]
For example when you chose "Stack relative to prop" and set a little bit of pitch a circular stacking is expected, however this does not happen, as the position is not incremented with the delta in every stack:

https://drive.google.com/file/d/0B6vgydhudtoAUjR3aHZUN2w0Sm8/view?usp=sharing

As you can see the first ghosted car is ok, but the second has missing some Z offset.

I think this piece of code in "TOOL:LeftClick(Trace)" has to be adjusted a little:
```
		if ( i == 1 or ( mode == MODE_PROP and stackRelative ) ) then
			stackdir, height, thisoffset = self:StackerCalcPos( lastEnt, mode, dir, offset )
		end
		
		entPos = entPos + stackdir * height + thisoffset
entAng = entAng + rotate
```
As well as in the ghosting inside the function "function TOOL:StackerCalcPos( ent, mode, dir, offset )"
Probably the variable "thisoffset" ( row 980 ) is not calculated correctly.

**Comment by Mista-Tea** [comment]
Based on your screenshot, I believe you need to check "Stack relative to new rotation".

**Comment by dvdvideo1234** [comment]
Thanks, i will be sure to try it out  ;)

**Comment by Mista-Tea** [comment]
The client's value is obtained here https://github.com/Mista-Tea/improved-stacker/blob/master/lua/weapons/gmod_tool/stools/stacker.lua#L963 and used here https://github.com/Mista-Tea/improved-stacker/blob/master/lua/weapons/gmod_tool/stools/stacker.lua#L979

You should definitely notice a difference when the setting is enabled.

**Comment by Mista-Tea** [comment]
Can you give me an update on whether enabling stacker_recalc resolved the issue? Thanks!

**Comment by dvdvideo1234** [comment]
I can check this today's evening, as I was at a holiday ;)

**Comment by dvdvideo1234** [comment]
Hi, this s indeed true. Thanks for sharing, but I've got another problem related to stacking.

Then the stack count is "30", and rotation pitch is "-7.94", the 30-th prop's rotation goes above 180:
https://drive.google.com/file/d/0B6vgydhudtoATklHV3VjVG4wVEk/view?usp=sharing

The 29-th prop's rotation is below 180 and it stacks just fine as I trace it:
https://drive.google.com/file/d/0B6vgydhudtoAMDc2eTFtN2lWcEU/view?usp=sharing

May be you could save initial forward, right, up vectors in that case and rotate the start angle around them. Using "Angle:RotateAroundAxis()", that way this problem will not be possible ;)
https://wiki.garrysmod.com/page/Angle/RotateAroundAxis

**Comment by Mista-Tea** [comment]
I'm going to close this and open a new issue to keep things organized.
