### ISSUE TITLE
TOOL:StackerCalcPos() returns inconsistent position vectors at certain rotation angles

### ISSUE THREAD

**Issue by Mista-Tea** [Mista-Tea/improved-stacker#17]
As per https://github.com/Mista-Tea/improved-stacker/issues/16#issuecomment-236715992

Stacked entities are not being positioned/angled correctly when trying to stack more props off an existing stack.

[Creating a stack](https://i.gyazo.com/b8d0e0b2f4c3705c360def4374cf0214.png)
[Correctly positioned/angle props off existing stack](https://i.gyazo.com/53a9588a0eada63dfdac98da9b37b81f.png)
[Incorrectly positioned/angled props off existing stack]
(https://i.gyazo.com/bf8c30bc88cd7a181ded57206ad1a724.png)

Problem exists on both v1.0 and v2.0.

**Comment by Mista-Tea** [comment]
This is fixed in v2.0 now (unreleased): [demo](https://i.gyazo.com/23f800bcf35b3c17dc69177f1ce41990.gif)

I could either push this out to v1.0 on here and the workshop, or wait until a public release of v2.0.

**Comment by Mista-Tea** [comment]
@dvdvideo1234 could you try out the latest revision of the [dev branch](https://github.com/Mista-Tea/improved-stacker/tree/dev) and see if this resolves the issue for you without any unexpected results?

The commit in particular is [here](https://github.com/Mista-Tea/improved-stacker/commit/85de463a2ed537e0de31e0832d8a705e5b438516) if you'd like to see what was changed.

**Comment by dvdvideo1234** [comment]
Ok, no problem. As soon as I get home, as I am currently at work and do not have a Gmod copy at disposal ;). I see you are using the function. It is awesome. I use it for the TA too at [2820]

https://github.com/dvdvideo1234/TrackAssemblyTool/blob/master/lua/trackassembly/trackasmlib.lua

**Comment by dvdvideo1234** [comment]
Hi, what's up. Checked it right away

The coordinate system of the prop:
https://drive.google.com/file/d/0B6vgydhudtoALTV0MjFaUkFEdGs/view?usp=sharing

The coordinate system of the world
https://drive.google.com/file/d/0B6vgydhudtoAbTZ4Y3VNY21NRVk/view?usp=sharing

Ghosting with pitch  < 180
https://drive.google.com/file/d/0B6vgydhudtoAS1RRUldnSGVyMzQ/view?usp=sharing

Ghosting with pitch  > 180
https://drive.google.com/file/d/0B6vgydhudtoAdUVQV0ZiYnpDRDg/view?usp=sharing

Though I think it it is anti-intuitive to stack to the left when YAW amount is positive and the slider knob is placed to the right relative to the panel:
https://drive.google.com/file/d/0B6vgydhudtoAbV9BSWk5alhialU/view?usp=sharing

 I think this can be fixed easily using:

entAng:RotateAroundAxis( entAng:Up(),     -rotate.y )

**Comment by Mista-Tea** [comment]
Yaw changed in https://github.com/Mista-Tea/improved-stacker/commit/865721e11bfaa883bd801207a1929195cfd523f5

**Comment by dvdvideo1234** [comment]
What about the other place ...

https://github.com/Mista-Tea/improved-stacker/blob/865721e11bfaa883bd801207a1929195cfd523f5/lua/weapons/gmod_tool/stools/stacker.lua#L683
