### ISSUE TITLE
You've hit the prop limit

### ISSUE THREAD

**Issue by USFClarence** [Mista-Tea/improved-stacker#22]
It says this once I have 100 props and try to stack something. I have changed the limits to things much higher through the menu and convars. My rank's prop limit is 10000000000. I can still spawn props but not stack them.

**Comment by Mista-Tea** [comment]
Hi VXGGOVORTEXGaming, thanks for taking the time to submit your issue.

With the information you've given me, I did a quick test and:
1. Loaded into singleplayer
2. Ensured the `Utilities -> Stacker - Improved` preset was set to **Singleplayer** ([image](https://i.gyazo.com/dc1925b3f9585ca5f6bc48f1f9987d88.png))
3. Spawned exactly 100 props, verified via `lua_run_cl print(LocalPlayer():GetCount("props"))`
4. Tried to stack more props

I didn't run into any error like "You've hit the prop limit".


Can you provide some additional details?
1. Are you encountering this problem in **singleplayer** or **multiplayer**?
2. What (if any) prop protection/admin system are you using?
3. What are your current serverside settings for Stacker? (You can just take a screenshot of the menu like [here](https://i.gyazo.com/dc1925b3f9585ca5f6bc48f1f9987d88.png))

**Comment by VXGGOVORTEXGaming** [comment]
Multiplayer, Falco's Prop Protection, ULX. Prop limit is set to 2048 in the tool config.

**Comment by Mista-Tea** [comment]
I realize this is a bit old, but did you ever resolve this on your end, and if so, how?

If not, there's a possibility the change I made in the dev branch for URS compatibility may solve the issue here, if you're willing to try it out: https://steamcommunity.com/linkfilter/?url=https://github.com/Mista-Tea/improved-stacker/tree/dev
