### ISSUE TITLE
Stacker processes SENTS of different class as prop_physics. 

### ISSUE THREAD

**Issue by dvdvideo1234** [Mista-Tea/improved-stacker#32]
Hello,

I regularly use the stacker tool, and sometimes it drives me nuts when I want to stack my personal scripted entities. These [`SENTS`](https://wiki.garrysmod.com/page/Scripted_Entities) always have the same model and collisions, but the server-side think hook is not duplicated, because the tool uses the ['ents.Create(strClass)'](https://wiki.garrysmod.com/page/ents/Create) [here](https://github.com/Mista-Tea/improved-stacker/blob/master/lua/weapons/gmod_tool/stools/stacker_improved.lua#L701). It seems this has to be populated dynamically with ['eSENT:getClass()'](https://wiki.garrysmod.com/page/Entity/GetClass)

Recently I created a PR #25, which I believe fixes this and [can be located here](https://github.com/Mista-Tea/improved-stacker/pull/25). If it's OK with you would you please merge it, so I can be able to stack my SENTs like the [`Stacker Advanced`](https://garrysmods.org/browse/tag/stacker)

**Comment by Mista-Tea** [comment]
Hey, I'm sorry for not addressing the PR in a timely manner.

I support being able to stack entities other than just prop_physics, but not as a default enabled option. It's very unsafe to give players the ability to stack any type of entity they want, e.g. NPCs, weapons, ragdolls, SENTs. It causes a lot of undefined behavior (like stacking E2s or wire components in general), and can cause a lot of mingey or game breaking scenarios for multiplayer servers.

I can understand maybe allowing anything to be stacked in *singleplayer*, given that not everything will work as intended. But for multiplayer, I would probably make a convar with different levels of entity type whitelists - e.g., default is prop_physics, next includes safe(ish) types like prop_effect, last would be all types.

**Comment by dvdvideo1234** [comment]
No worries. I just wanted to [let you know](https://github.com/Mista-Tea/improved-stacker/blame/master/README.md#L6) instead of fixing it myself in SP for only my specific case. I think I better wait for you to figure this out and solve this however you think is right! ;)
