### ISSUE TITLE
optimize your PostDrawTranslucentRenderables  hook

### ISSUE THREAD

**Issue by storm37000** [Mista-Tea/improved-stacker#38]
your PostDrawTranslucentRenderables hook inside the tool needs to be optimized as it uses not an insignificant amount of client fps/cpu.  The simplest way to optimize would be to move the ply:GetActiveWeapon() block up as far as it can go, at least above the eye trace as that is an expensive function to run on every frame even while the tool isnt being used.  visclip has a smilar issue.

**Comment by storm37000** [comment]
yes, dbugr is a hook profiler.  ive used all 3 of the major profilers/detectors

**Comment by Mista-Tea** [comment]
Sorry for the delay, I've pushed the changes to reduce the unnecessary hook runtime. I'll update the workshop version next.

Thanks for bringing this to my attention!
