### ISSUE TITLE
Ability to let objects go through world

### ISSUE THREAD

**Issue by LucaTanks** [Mista-Tea/improved-stacker#40]

**Comment by DaBigEgg** [comment]
My suggestion

**Comment by Mista-Tea** [comment]
You can already control whether stacked props are allowed to be created through worldspace or not.

From In-game console, as an admin: `stacker_improved_set_force_stayinworld 0`

From SRCDS console: `stacker_improved_force_stayinworld 0`

From in-game menu, as an admin: https://steamuserimages-a.akamaihd.net/ugc/480019612574925873/A66A3E1D385B3EF213A01B859E70603939C8AE7B/
Very last option ("Stay in World")
