### ISSUE TITLE
Language files aren't working, causing internal names to show up.

### ISSUE THREAD

**Issue by glockcodes** [Mista-Tea/improved-stacker#49]
[Improved Stacker] lua/weapons/gmod_tool/stools/stacker_improved.lua:220: bad argument #2 to 'Add' (string expected, got nil)
1. Add - [C]:-1
2. unknown - lua/weapons/gmod_tool/stools/stacker_improved.lua:220
3. include - [C]:-1
4. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/stool.lua:154
5. include - [C]:-1
6. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:372
7. include - [C]:-1
8. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/cl_init.lua:11

Language files aren't working, causing internal names to show up. Spawnmenu settings have vanished entirely, making it impossible to configure. Prop previews also aren't working with this tool.

**Comment by dvdvideo1234** [comment]
Hi, @Mista-Tea 

I recall having such issues when coding the [track assembly tool](https://github.com/dvdvideo1234/TrackAssemblyTool). That's why I switched to using [`*.property`](https://wiki.facepunch.com/gmod/Addon_Localization) files. As every server may have its configuration done differently, I suppose the library may not get included properly in some cases. Later I was using [`language.GetPhrase`](https://wiki.facepunch.com/gmod/language.GetPhrase) to retrieve the translations.

**Comment by dvdvideo1234** [comment]
In this case fails: `language.Add( "tool."..mode..".0",            L(prefix.."0") )`, where [translation keys is defined here](https://github.com/Mista-Tea/improved-stacker/blob/master/lua/improvedstacker/localization.lua). I cannot find any value labeled `prefix.."0"` and our return key is missing in this case so we receive a nil `value`:
```lua
function Localize(key, lang, returnKey)
  if (lang and not IsValidLanguage(lang)) then
    error("Invalid language provided ('" .. tostring(lang) .. "')")
    return
  end

  local tbl = localizations[(lang and lang:lower()) or GetLocale()]

  return (tbl and tbl[key]) -- If there is a bind, return it
  or (returnKey and key) -- If there is no bind and we want to return the key on failure, return the key
  or (localizations[FALLBACK] and localizations[FALLBACK][key]) -- If there is a bind in the fallback language, return it
  or nil -- Otherwise return nil
end
```

**Comment by dvdvideo1234** [comment]
Hello, @glockcodes, if you in a hurry to test this, please use branch:
https://github.com/dvdvideo1234/improved-stacker/tree/local-name

**Comment by Mista-Tea** [comment]
Fixed in https://github.com/Mista-Tea/improved-stacker/commit/827bfb24deff2b2cfb965d196d34881a9a429f02 due to language.Add changes requiring non-nil arguments. Let me know if anything else comes up in the meantime, and thank you for bringing this to my attention.
